2025-09-17 16:46:43,619 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:43,620 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:46:45,661 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:45,661 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:46:47,700 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:47,701 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:46:49,741 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:49,741 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:46:51,779 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:51,779 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:46:53,818 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:53,818 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:46:55,859 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:55,859 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:46:57,897 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:57,897 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:46:59,937 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:46:59,937 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:47:01,975 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:47:01,975 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:47:04,014 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:47:04,014 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-17 16:47:06,053 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-17 16:47:06,053 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:01,239 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:01,239 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:03,280 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:03,280 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:05,319 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:05,319 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:07,359 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:07,360 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:09,400 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:09,401 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:11,440 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:11,440 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:13,479 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:13,479 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:15,519 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:15,519 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:17,560 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:17,560 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:19,600 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:19,600 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:21,641 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:21,641 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:23,681 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:23,681 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:25,739 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:25,739 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:27,797 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:27,797 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:29,854 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:29,855 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:31,912 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:31,912 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:33,968 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:33,968 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:36,028 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:36,028 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:38,085 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:38,085 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:40,143 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:40,143 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:42,199 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:42,200 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:44,258 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:44,258 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:46,313 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:46,314 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:48,371 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:48,371 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:50,426 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:50,427 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:52,484 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:52,484 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:54,539 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:54,539 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:56,596 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:56,596 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:15:58,651 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:15:58,651 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:00,707 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:00,707 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:02,763 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:02,763 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:04,819 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:04,820 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:06,878 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:06,878 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:08,934 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:08,934 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:10,990 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:10,991 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:13,045 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:13,046 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:15,102 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:15,103 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:17,159 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:17,159 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:19,216 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:19,216 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:21,274 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:21,274 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:23,333 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:23,333 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:25,391 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:25,392 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:27,449 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:27,449 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:29,507 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:29,507 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:31,562 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:31,562 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:33,619 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:33,620 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:35,677 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:35,677 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:37,736 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:37,736 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:39,794 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:39,794 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:41,851 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:41,851 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:43,907 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:43,907 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:45,963 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:45,964 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:48,020 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:48,020 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:50,078 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:50,078 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:52,135 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:52,135 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:54,191 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:54,191 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:56,247 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:56,247 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:16:58,304 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:16:58,304 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:00,362 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:00,362 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:02,419 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:02,419 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:04,476 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:04,477 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:06,533 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:06,533 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:08,593 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:08,593 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:10,649 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:10,649 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:12,708 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:12,708 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:14,766 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:14,766 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:16,824 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:16,824 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:18,880 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:18,880 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:20,938 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:20,938 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:22,995 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:22,995 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:25,052 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:25,052 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:27,108 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:27,108 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:29,165 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:29,165 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:31,222 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:31,223 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:33,279 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:33,279 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:35,335 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:35,336 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:37,392 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:37,392 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:39,449 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:39,449 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:41,504 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:41,505 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:43,563 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:43,563 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:45,619 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:45,619 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:47,678 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:47,678 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:49,735 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:49,736 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:51,793 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:51,793 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:53,852 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:53,852 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:55,909 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:55,910 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:17:57,968 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:17:57,968 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:00,026 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:00,026 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:02,084 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:02,085 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:04,143 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:04,144 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:06,203 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:06,203 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:08,260 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:08,260 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:10,316 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:10,316 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:12,374 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:12,375 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:14,431 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:14,431 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:16,489 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:16,489 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:18,545 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:18,545 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:20,603 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:20,603 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:22,659 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:22,659 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:24,717 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:24,718 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:26,776 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:26,776 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:28,834 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:28,834 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:30,891 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:30,891 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:32,949 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:32,949 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:35,006 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:35,007 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:37,066 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:37,066 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:39,123 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:39,124 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:41,181 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:41,182 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:43,239 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:43,239 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:45,298 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:45,298 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:47,356 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:47,356 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:49,414 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:49,414 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:51,466 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:51,466 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:53,518 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:53,518 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:55,572 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:55,572 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:57,626 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:57,626 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:18:59,678 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:18:59,678 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:01,732 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:01,732 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:03,784 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:03,785 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:05,839 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:05,839 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:07,892 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:07,892 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:09,946 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:09,946 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:11,995 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:11,995 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:14,046 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:14,046 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:16,098 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:16,098 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:18,148 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:18,148 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:20,200 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:20,201 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:22,253 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:22,253 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:24,308 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:24,309 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:26,363 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:26,363 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:28,413 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:28,414 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:30,465 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:30,465 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:32,517 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:32,517 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:34,571 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:34,571 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:36,624 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:36,625 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:38,676 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:38,676 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:40,728 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:40,728 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:42,780 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-18 09:19:42,780 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-18 09:19:42,780 - __main__ - CRITICAL - Connection timeout. Rebooting.
2025-09-18 10:29:07,853 - __main__ - CRITICAL - The error is: list assignment index out of range
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 379, in main
    results[pos] = counts
    ~~~~~~~^^^^^
IndexError: list assignment index out of range
2025-09-18 10:33:15,181 - __main__ - CRITICAL - The error is: unsupported operand type(s) for +: 'int' and 'list'
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 398, in main
    total += sum(counts)
             ^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'list'
2025-09-18 10:57:34,045 - __main__ - ERROR - some error in publish!,name 'camera_no' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1024, in client_publish
    if camera_no is not None and detectObj != 0 and camera != 0:
       ^^^^^^^^^
NameError: name 'camera_no' is not defined
2025-09-18 10:57:37,060 - __main__ - ERROR - some error in publish!,name 'camera_no' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1024, in client_publish
    if camera_no is not None and detectObj != 0 and camera != 0:
       ^^^^^^^^^
NameError: name 'camera_no' is not defined
2025-09-18 10:57:40,069 - __main__ - ERROR - some error in publish!,name 'camera_no' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1024, in client_publish
    if camera_no is not None and detectObj != 0 and camera != 0:
       ^^^^^^^^^
NameError: name 'camera_no' is not defined
2025-09-18 11:32:09,600 - __main__ - ERROR - some error in publish!,0
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1025, in client_publish
    value = frame_counts[0] if len(frame_counts) > 0 else 0  # Area1
            ~~~~~~~~~~~~^^^
KeyError: 0
2025-09-18 11:32:12,619 - __main__ - ERROR - some error in publish!,0
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1025, in client_publish
    value = frame_counts[0] if len(frame_counts) > 0 else 0  # Area1
            ~~~~~~~~~~~~^^^
KeyError: 0
2025-09-18 11:32:15,674 - __main__ - ERROR - some error in publish!,0
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1025, in client_publish
    value = frame_counts[0] if len(frame_counts) > 0 else 0  # Area1
            ~~~~~~~~~~~~^^^
KeyError: 0
2025-09-18 11:34:44,320 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:34:47,346 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:34:50,389 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:34:53,397 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:34:56,416 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:34:59,425 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:35:02,439 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:35:05,447 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:35:08,456 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
    if cameraNO != 0 and detectObj != 0:
       ^^^^^^^^
NameError: name 'cameraNO' is not defined
2025-09-18 11:35:11,482 - __main__ - ERROR - some error in publish!,name 'cameraNO' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 109, in result_sending
    mqtt.client_publish(information['results'], information['images'])
  File "/home/user/Aicam-Area/mq_connector.py", line 1017, in client_publish
NameError: name 'cameraNO' is not defined
2025-09-18 14:13:45,785 - camera - ERROR - Error adding 15 FPS IP camera: 'PolygonStore' object has no attribute 'assign_id'
Traceback (most recent call last):
  File "/home/user/Aicam-Area/camera.py", line 450, in add_ip_camera_optimized
    polygon_store.assign_id(cameraNO)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PolygonStore' object has no attribute 'assign_id'
2025-09-18 14:13:47,309 - camera - ERROR - Error adding webcam: 'PolygonStore' object has no attribute 'assign_id'
Traceback (most recent call last):
  File "/home/user/Aicam-Area/camera.py", line 408, in add_webcam_pi_camera
    polygon_store.assign_id(cameraNO)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PolygonStore' object has no attribute 'assign_id'
2025-09-18 14:16:48,304 - camera - ERROR - Error adding 15 FPS IP camera: 'PolygonStore' object has no attribute 'save'
Traceback (most recent call last):
  File "/home/user/Aicam-Area/camera.py", line 451, in add_ip_camera_optimized
    polygon_store.save()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PolygonStore' object has no attribute 'save'
2025-09-18 14:16:49,836 - camera - ERROR - Error adding webcam: 'PolygonStore' object has no attribute 'save'
Traceback (most recent call last):
  File "/home/user/Aicam-Area/camera.py", line 409, in add_webcam_pi_camera
    polygon_store.save()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PolygonStore' object has no attribute 'save'
2025-09-19 09:28:55,075 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-19 09:28:55,078 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-19 09:28:57,117 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-19 09:28:57,117 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-19 09:28:59,172 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-19 09:28:59,172 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-19 09:29:01,225 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-19 09:29:01,225 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-19 09:29:03,282 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-19 09:29:03,282 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-19 09:29:05,336 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-19 09:29:05,337 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-19 09:29:07,392 - devicecare - ERROR - Failed to connect WiFi: dlink-BCD8 (code 10)
2025-09-19 09:29:07,392 - devicecare - ERROR - stderr: Error: No network with SSID 'dlink-BCD8' found.
2025-09-19 09:29:09,395 - devicecare - ERROR - Exception while connecting to WiFi: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/user/Aicam-Area/devicecare.py", line 53, in Connection_wifi
    subprocess.run(['/usr/bin/sudo', 'nmcli', 'connection', 'delete', ssid], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/home/user/Aicam-Area/env_setup.py", line 127, in _guard_run
    return _orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Aicam-Area/env_setup.py", line 133, in _guard_popen
    return _orig_popen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1834, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
2025-09-19 09:29:11,404 - devicecare - ERROR - Exception while connecting to WiFi: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/user/Aicam-Area/devicecare.py", line 53, in Connection_wifi
    subprocess.run(['/usr/bin/sudo', 'nmcli', 'connection', 'delete', ssid], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/home/user/Aicam-Area/env_setup.py", line 127, in _guard_run
    return _orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Aicam-Area/env_setup.py", line 133, in _guard_popen
    return _orig_popen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1834, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
2025-09-19 09:29:13,409 - devicecare - ERROR - Exception while connecting to WiFi: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/user/Aicam-Area/devicecare.py", line 53, in Connection_wifi
    subprocess.run(['/usr/bin/sudo', 'nmcli', 'connection', 'delete', ssid], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/home/user/Aicam-Area/env_setup.py", line 127, in _guard_run
    return _orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Aicam-Area/env_setup.py", line 133, in _guard_popen
    return _orig_popen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1834, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
2025-09-19 09:29:15,413 - devicecare - ERROR - Exception while connecting to WiFi: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/user/Aicam-Area/devicecare.py", line 53, in Connection_wifi
    subprocess.run(['/usr/bin/sudo', 'nmcli', 'connection', 'delete', ssid], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/home/user/Aicam-Area/env_setup.py", line 127, in _guard_run
    return _orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Aicam-Area/env_setup.py", line 133, in _guard_popen
    return _orig_popen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1834, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
2025-09-19 09:33:21,894 - camera - ERROR - Failed to start 15 FPS IP camera 6
2025-09-19 09:33:58,654 - camera - ERROR - Failed to start 15 FPS IP camera 6
2025-09-19 12:20:34,171 - __main__ - CRITICAL - The error is: name 'update_rtsp_stream_by_index' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 466, in main
    update_rtsp_stream_by_index(frames_by_no, cam_ids, current_stream["selected_cam"])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'update_rtsp_stream_by_index' is not defined
2025-09-19 12:21:30,576 - __main__ - CRITICAL - The error is: name 'update_rtsp_stream' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 466, in main
    update_rtsp_stream(frames_by_no, cam_ids, current_stream["selected_cam"])
    ^^^^^^^^^^^^^^^^^^
NameError: name 'update_rtsp_stream' is not defined
2025-09-19 13:21:26,522 - __main__ - CRITICAL - The error is: 'selected_cam'
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 400, in main
    selected_cam = current_stream["selected_cam"]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'selected_cam'
2025-09-19 14:08:35,262 - __main__ - CRITICAL - The error is: 'selected_cam'
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 460, in main
    print("🔎 selected_cam =", current_stream["selected_cam"],
                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'selected_cam'
2025-09-19 15:18:34,636 - __main__ - CRITICAL - The error is: name 'recorder' is not defined
Traceback (most recent call last):
  File "/home/user/Aicam-Area/main.py", line 488, in main
    recorder.record_video_dict(frames_by_no)
    ^^^^^^^^
NameError: name 'recorder' is not defined
